### ISSUE TITLE
latest stable gradle build of orion 0.1 crashes with latest dev gradle build of meteor 0.4.7 if autogap module is active

### ISSUE THREAD

**Issue by ecstaticpanic** [AntiCope/orion#2]
```
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Module.isActive()" because "module" is null
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.startEating(AutoGap.java:187)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.onTick(AutoGap.java:167)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap$$Lambda$6595/0x00000000dfdf1370.accept(Unknown Source)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zki000$onPreTick(class_310.java:4600)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.startEating(AutoGap.java:187)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.onTick(AutoGap.java:167)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap$$Lambda$6595/0x00000000dfdf1370.accept(Unknown Source)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zki000$onPreTick(class_310.java:4600)

-- Affected level --
Details:
	All players: 1 total; [class_746['<ACCESS TOKEN>'/1, l='ClientLevel', x=-115.69, y=4.00, z=-19.61]]
	Chunk stats: 256, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,4,-16), Section: (at 0,4,0 in -8,0,-1; chunk contains blocks -128,0,-16 to -113,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 966 game time, 966 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Mac OS X (x86_64) version 12.0.1
	Java Version: 16.0.2, International Business Machines Corporation
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Mac OS X amd64-64-Bit Compressed References 20210729_66 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 34df42439f3 based on jdk-16.0.2+7), Eclipse OpenJ9
	Memory: 345577720 bytes (329 MiB) / 1412038656 bytes (1346 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 11
	Microarchitecture: whiskey Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 520
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x191b
	Graphics card #0 versionInfo: Revision ID: 0x0007
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 5713.59
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 37.75
	JVM Flags: 5 total; -Xoptionsfile=/Library/Java/JavaVirtualMachines/ibm-semeru-open-16.jdk/Contents/Home/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xms204m -Xmx4096m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 530 GL version 4.1 INTEL-18.2.10, Intel Inc.
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	Player Count: 1 / 8; [class_3222['<ACCESS TOKEN>'/1, l='ServerLevel[New World]', x=-115.69, y=4.00, z=-19.61]]
	Data Packs: vanilla (incompatible)

-- Meteor Client --
Version: 0.4.7

[Combat]:
Auto Armor (auto-armor)
Auto Totem (auto-totem)
Criticals (criticals)

[Player]:
Auto Gap (auto-gap)
Auto Replenish (auto-replenish)
Auto Tool (auto-tool)
Chest Swap (chest-swap)
Fast Use (fast-use)
No Mining Trace (no-mining-trace)

[Movement]:
Anchor (anchor)
Elytra Fly (elytra-fly)
Gui Move (gui-move)
No Slow (no-slow)
Speed (speed)
Velocity (velocity)

[Render]:
Better Tooltips (better-tooltips)
Block Selection (block-selection)
Boss Stack (boss-stack)
Break Indicators (break-indicators)
Camera Tweaks (camera-tweaks)
Chams (chams)
City Esp (city-esp)
Entity Owner (entity-owner)
Fullbright (fullbright)
HUD (HUD)
Hole Esp (hole-esp)
Item Highlight (item-highlight)
Logout Spots (logout-spots)
Nametags (nametags)
No Render (no-render)
Storage Esp (storage-esp)
Tracers (tracers)
Trajectories (trajectories)
Unfocused Cpu (unfocused-cpu)
Wall Hack (wall-hack)

[World]:
Ambience (ambience)

[Misc]:
Message Aura (message-aura)

#@!@# Game crashed! Crash report saved to: #@!@# /Applications/UltimMC.app/Data/instances/1.17.1/.minecraft/crash-reports/crash-2021-11-12_02.26.24-client.txt
[02:26:24] [Thread-8/INFO]: Saving
Process exited with code 255.
```

**Comment by C10udburst** [comment]
does this happen without orion? because I don't see any mention of it in the stacktrace.

**Comment by ecstaticpanic** [comment]
> does this happen without orion? because I don't see any mention of it in the stacktrace.

can confirm this does not happen without orion addon

**Comment by ecstaticpanic** [comment]
the `java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Module.isActive()" because "module" is null` gave me an impression that this has something to do with the active module list in hud, so i tried making it visible on activation and vice versa - no difference, still crashes. the settings of the autogap module are default, except for health threshold of 14, if that helps

**Comment by ecstaticpanic** [comment]
i should also clarify by 'when autogap module is active' i mean not when it is activated as a module, but when it is in a circumstance of use

**Comment by ecstaticpanic** [comment]
tried latest orion release - same crash log. also tried latest stable release of meteor 0.4.6 - same crash log

**Comment by ecstaticpanic** [comment]
exact same crash log even on liberica openjdk 17.0.1
confirmed to be reproducible on 0.4.6 and 0.4.7 versions of meteor with the orion addon, on two different versions of jvms - adoptopenjdk 16 openj9 and liberica openjdk 17, so this error only happens if orion addon is installed. meteor is not to blame, autogap otherwise works perfectly fine
