### ISSUE TITLE
[Bug] Crashes when i launch my game

### ISSUE THREAD

**Issue by Fr0go1** [AntiCope/orion#44]
### Describe the bug

When i use it it crashes my game when i load

### Crashlog

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-11-15 21:59:58
Description: Initializing game

java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_30613(java.io.File, net.minecraft.class_2505)'
	at net.minecraft.class_315.handler$zlh000$fabric-resource-loader-v0$onLoad(class_315.java:2360)
	at net.minecraft.class_315.method_1636(class_315.java:1481)
	at net.minecraft.class_315.<init>(class_315.java:1237)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Steps to reproduce

1. Launch the game

### Operating System

Windows

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Other mods

```plaintext
orion-0.2
InGameAccountSwitcher-Fabric-1.20.2-8.0.2
ViaFabric-0.4.11+49-dev
blackout-1.0.2
1trouser-streak-0.7.2-1.20.2
meteor-client-0.5.5-1977
starlight-1.1.3+fabric.5867eae
baritone-1.20.2-20231022.115809-1
fabric-api-0.90.7+1.20.2
meteor-plus-1.0.4
Numby-Hack-2.2
modmenu-8.0.0
lithium-fabric-mc1.20.2-0.12.0
ferritecore-6.0.1-fabric
litematica-fabric-1.20.2-0.16.0
malilib-fabric-1.20.2-0.17.0
```

**Comment by jwaxy** [comment]
It happens on me too

**Comment by GoofyBoi420** [comment]
idk try removing fabric api

**Comment by ghost** [comment]
yeah i also have this crash

**Comment by Pdam67** [comment]
Seems to be trying to access a class that doesn't exist anymore?

**Comment by MuddyGiraffe347** [comment]
i also have the crash as well
